--DADOS SQL

IF OBJECT_ID('CATEGORIAS') IS NULL
BEGIN
	CREATE TABLE CATEGORIAS
	(
		CATEGORIA_ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		DESCRICAO VARCHAR(50) NULL
	)
END

IF OBJECT_ID('CLIENTES') IS NULL
BEGIN
	CREATE TABLE CLIENTES
	(
		CLIENTE_ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		NOME VARCHAR(50) NULL,
		ENDERECO VARCHAR(250) NULL,
		CIDADE VARCHAR(250) NULL,
		BAIRRO VARCHAR(100) NULL,
		ESTADO VARCHAR(2) NULL,
		CEP VARCHAR(10) NULL,
		TELEFONE VARCHAR(14) NULL,
		EMAIL VARCHAR(250) NULL,
		DATA_NASCIMENTO DATETIME NULL
	)
END

IF OBJECT_ID('PRODUTOS') IS NULL
BEGIN
	CREATE TABLE PRODUTOS
	(
		PRODUTO_ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		NOME VARCHAR(50) NULL,
		DESCRICAO VARCHAR(250) NULL,
		VALOR DECIMAL(19,6) NULL,
		QUANTIDADE DECIMAL(19,6) NULL,
		CATEGORIA_ID INT NULL

		CONSTRAINT FK_PROUTOS_CATEGORIAS
		FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(CATEGORIA_ID)
	)
END

IF OBJECT_ID('VENDAS') IS NULL
BEGIN
	CREATE TABLE VENDAS
	(
		VENDA_ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		CLIENTE_ID INTEGER NOT NULL,
		DATA_VENDA DATETIME DEFAULT GETDATE(),
		TOTAL_VENDA DECIMAL(19,6)

		CONSTRAINT FK_VENDAS_CLIENTES
		FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
	)
END

IF OBJECT_ID('VENDAS_ITENS') IS NULL
BEGIN
	CREATE TABLE VENDAS_ITENS
	(
		VENDA_ID INTEGER NOT NULL,
		PRODUTO_ID INTEGER NOT NULL,
		VALOR_UNITARIO DECIMAL(19,6),
		QUANTIDADE DECIMAL(19,6),
		TOTAL_PRODUTO DECIMAL(19,6)

		PRIMARY KEY(VENDA_ID,PRODUTO_ID)
		CONSTRAINT FK_VENDAS_ITENS_PRODUTOS
		FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID)
	)
END